import type { ProgramData } from './types';

/**
 * Mock data matching the C450 program structure.
 * Used in development mode when no Moodle token is provided.
 */
export const MOCK_PROGRAM: ProgramData = {
  id: 1,
  shortname: 'C450',
  fullname: 'C450',
  sun: {
    id: 99,
    shortname: 'C450-OS',
    label: 'Open Scentia',
    fullname: 'Open Scentia',
    status: 'completed',
    progress: 100,
    courseUrl: '#',
    icon: 'sun',
  },
  units: [
    {
      id: 100,
      shortname: 'C450-U0',
      label: 'U0',
      fullname: 'C450 – Unidad 0. Plataforma de lanzamiento',
      status: 'completed',
      progress: 100,
      courseUrl: '#',
      icon: 'flag',
    },
    {
      id: 101,
      shortname: 'C450-U1',
      label: 'U1',
      fullname: 'C450 – Unidad 1. Lanzamiento de señal',
      status: 'completed',
      progress: 100,
      courseUrl: '#',
      icon: 'signal',
    },
    {
      id: 102,
      shortname: 'C450-U2',
      label: 'U2',
      fullname: 'C450 – Unidad 2. Preparado para mover',
      status: 'completed',
      progress: 100,
      courseUrl: '#',
      icon: 'car',
    },
    {
      id: 103,
      shortname: 'C450-U3',
      label: 'U3',
      fullname: 'C450 – Unidad 3. Visión de túnel',
      status: 'in-progress',
      progress: 45,
      courseUrl: '#',
      icon: 'tunnel',
    },
    {
      id: 104,
      shortname: 'C450-U4',
      label: 'U4',
      fullname: 'C450 – Unidad 4. Análisis profundo',
      status: 'locked',
      progress: 0,
      courseUrl: '#',
      icon: 'search',
    },
    {
      id: 105,
      shortname: 'C450-U5',
      label: 'U5',
      fullname: 'C450 – Unidad 5. Señales inteligentes',
      status: 'locked',
      progress: 0,
      courseUrl: '#',
      icon: 'signal',
    },
    {
      id: 106,
      shortname: 'C450-U6',
      label: 'U6',
      fullname: 'C450 – Unidad 6. Respuesta a emergencias',
      status: 'locked',
      progress: 0,
      courseUrl: '#',
      icon: 'alert',
    },
    {
      id: 107,
      shortname: 'C450-MC',
      label: 'Misión Control',
      fullname: 'C450 – Misión control',
      status: 'locked',
      progress: 0,
      courseUrl: '#',
      icon: 'trophy',
    },
  ],
};
